blueprint:
  name: Synchronize br and temp
  description: Synchronize the on/off state, brightness, and color temperature of 5 entities
  domain: automation
  input:
    linked_entities:
      name: Entities to link
      selector:
        entity:
          multiple: true
mode: queued
max_exceeded: silent
variables:
    linked_entities: !input 'linked_entities'
    
trigger:
  - platform: state
    entity_id: !input 'linked_entities'
  - platform: state
    entity_id: !input 'linked_entities'
    attribute: brightness
  - platform: state
    entity_id: !input 'linked_entities'
    attribute: color_temp
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ is_state(trigger.to_state.entity_id, "on") }}'
        sequence:
          - service: light.turn_on
            data:
              brightness: '{{ state_attr(trigger.to_state.entity_id, "brightness") }}'
              color_temp: >
                {% if trigger.to_state.attributes.color_temp is defined %}
                  {{ trigger.to_state.attributes.color_temp }}
                {% else %}
                  {{ state_attr(trigger.to_state.entity_id, "color_temp") }}
                {% endif %}
            target:
              entity_id: '{{ expand(linked_entities) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'
      - conditions:
          - condition: template
            value_template: '{{ is_state(trigger.to_state.entity_id, "off") }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: '{{ expand(linked_entities) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'
